# Generated by Django 3.0.8 on 2020-07-13 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('mob_no', models.IntegerField(primary_key=True, serialize=False)),
                ('real_name', models.CharField(max_length=100)),
                ('tz', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('start_time', models.DateTimeField(auto_now=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('order_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('shipping_date', models.DateField(blank=True, null=True)),
                ('mobile_no', models.CharField(max_length=15)),
                ('pickup_address', models.CharField(max_length=150)),
                ('dropoff_address', models.CharField(max_length=150)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='order.Member')),
            ],
        ),
    ]
