# Generated by Django 3.0.8 on 2020-07-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='request_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
