# Generated by Django 3.0.8 on 2020-07-13 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_track_request_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='orders',
            new_name='order_id',
        ),
    ]
